### ISSUE TITLE
[Crash] [1.9.4] Algorithm assimilator does not like Amethyst trees

### ISSUE THREAD

**Issue by hron84** [SonarSonic/Calculator#155]
I placed an Algorithm Assimilator next to an Amethyst tree on top of a cobblestone slab and this crash happened:

```
java.lang.NullPointerException: Ticking block entity
    at sonar.calculator.mod.common.tileentity.machines.TileEntityAssimilator$Algorithm.harvestBlock(TileEntityAssimilator.java:257)
    at sonar.calculator.mod.common.tileentity.machines.TileEntityAssimilator.func_73660_a(TileEntityAssimilator.java:61)
    at net.minecraft.world.World.func_72939_s(World.java:1797)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:707)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:148)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
    at java.lang.Thread.run(Thread.java:745)

{ ... snip ...}

[23:53:58] [Client thread/DEBUG] [FML/]: Mod sorting data
[23:53:58] [Client thread/DEBUG] [FML/]:    Aroma1997CoreHelper(Aroma1997Core|Helper:1.1.0.3): Aroma1997Core-1.9.4-1.1.0.3.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    AromaBackup(AromaBackup:1.0.1.1): AromaBackup-1.9.4-1.0.1.1.jar (required-after:Aroma1997Core)
[23:53:58] [Client thread/DEBUG] [FML/]:    AromaBackupAPI(API: AromaBackupAPI:1.0): AromaBackup-1.9.4-1.0.1.1.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    AromaBackupRecovery(AromaBackup Recovery:1.0): AromaBackup-1.9.4-1.0.1.1.jar (required-after:AromaBackup;required-after:Aroma1997Core)
[23:53:58] [Client thread/DEBUG] [FML/]:    bagginses(Bagginses:2.4.2d): Bagginses-1.9.4-2.5.3.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    Baubles(Baubles:1.2.1.0): Baubles-1.9.4-1.2.1.0.jar (required-after:Forge@[12.17.0,);)
[23:53:58] [Client thread/DEBUG] [FML/]:    betterbuilderswands(Better Builder's Wands:0.6.6): BetterBuildersWands-0.6.6-1.9.4r143+f4959e8.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    Botania(Botania:r1.8-313): Botania-unofficial.r1.8-313.jar (required-after:Forge@[12.17.0.1965,];required-after:Baubles;after:Thaumcraft)
[23:53:58] [Client thread/DEBUG] [FML/]:    CoFHAPI(API: CoFHAPI:1.8.9R1.2.0B1): mcjtylib-1.10-1.9.9.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    CoFHAPI|energy(API: CoFHAPI|energy:1.8.9R1.2.0B1): mcjtylib-1.10-1.9.9.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    Waila(Waila:1.7.0): Waila-1.7.0-B3_1.9.4.jar (required-after:Forge@[12.16.0.1809,);)
[23:53:58] [Client thread/DEBUG] [FML/]:    WailaAPI(API: WailaAPI:1.3): Waila-1.7.0-B3_1.9.4.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    SonarCore(SonarCore:3.0.7): SonarCore-1.9.4-3.0.7.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    Calculator(Calculator:3.0.8): Calculator-1.9.4-3.0.8.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    Chameleon(Chameleon:1.9.4-2.1.6): Chameleon-1.9.4-2.1.6.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    ChiselAPI|Carving(API: ChiselAPI|Carving:0.0.1): Chisel-MC1.9.4-0.0.6.33.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    chisel(Chisel:MC1.9.4-0.0.6.33): Chisel-MC1.9.4-0.0.6.33.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    chiselsandbits(Chisels & Bits:10.16): chiselsandbits-10.16.jar (required-after:Forge@[12.17.0.1909,);after:mcmultipart;after:jei@[11.15.0.1697,))
[23:53:58] [Client thread/DEBUG] [FML/]:    ChiselsBytes(Chisels & Bytes:0.4): ChiselsBytes-1.9.4-0.4.jar (required-after:chiselsandbits)
[23:53:58] [Client thread/DEBUG] [FML/]:    cookingforblockheads(Cooking for Blockheads:3.1.26): CookingForBlockheads-mc1.9.4-3.1.26.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    craftingtweaks(Crafting Tweaks:5.0.6): craftingtweaks-mc1.9.4-5.0.6.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    ExtraUtils2(ExtraUtils2:1.0): extrautils2-1.9.4-alpha-1.0.0a.jar (required-after:Forge@[12.16.1.1887,);before:JEI@[2.24.2.125,))
[23:53:58] [Client thread/DEBUG] [FML/]:    GardenOfGlass(Garden of Glass:sqrt(-1)): GardenOfGlass.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    JEI(Just Enough Items:3.6.8.225): jei_1.9.4-3.6.8.225.jar (required-after:Forge@[12.17.0.1946,);)
[23:53:58] [Client thread/DEBUG] [FML/]:    journeymap(JourneyMap:1.9.4-5.2.4): journeymap-1.9.4-5.2.4-unlimited.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    ProjectE(ProjectE:1.9.4-PE1.0.4B): ProjectE-1.9.4-PE1.0.4B.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    McJtyLib(API: McJtyLib:1.10-1.9.9): mcjtylib-1.10-1.9.9.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    rftools(RFTools:5.07b): rftools-1.9.4-5.07b.jar (required-after:Forge@[12.16.1.1898,);required-after:McJtyLib@[1.10-1.9.9,))
[23:53:58] [Client thread/DEBUG] [FML/]:    roots(Roots:0.110): roots-1.9.4-0.110.0.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    StorageDrawers(Storage Drawers:1.9.4-3.2.1): StorageDrawers-1.9.4-3.2.1.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    storagenetwork(Storage Network:1.12.7): StorageNetwork-1.9.4-1.12.7.jar (required-after:Forge@[12.17.0.1957,);)
[23:53:58] [Client thread/DEBUG] [FML/]:    VTweaks(V-Tweaks:1.4.9.4): VTweaks-1.10.x-1.4.9.4.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    WailaHarvestability(Waila Harvestability:1.1.7): WailaHarvestability-mc1.9-1.1.7.jar (after:TConstruct;after:ExtraTiC;after:TSteelworks;after:Mariculture)
[23:53:58] [Client thread/DEBUG] [FML/]:    ICSE(I Can See Everything:1.1.0.0): Wawla-1.10.2-2.3.0.197.jar (after:Waila)
[23:53:58] [Client thread/DEBUG] [FML/]:    wawla(What Are We Looking At:2.3.0.194): Wawla-1.10.2-2.3.0.197.jar (after:ICSE)
[23:53:58] [Client thread/DEBUG] [FML/]:    ChiselsAndBitsAPI(API: ChiselsAndBitsAPI:11.7.0): chiselsandbits-10.16.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    StorageDrawersAPI(API: StorageDrawersAPI:1.7.10-1.2.0): StorageDrawers-1.9.4-3.2.1.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    StorageDrawersAPI|registry(API: StorageDrawersAPI|registry:1.7.10-1.2.0): StorageDrawers-1.9.4-3.2.1.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    StorageDrawersAPI|storage(API: StorageDrawersAPI|storage:1.7.10-1.2.0): StorageDrawers-1.9.4-3.2.1.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    StorageDrawersAPI|inventory(API: StorageDrawersAPI|inventory:1.7.10-1.2.0): StorageDrawers-1.9.4-3.2.1.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    BotaniaAPI(API: BotaniaAPI:79): Botania-unofficial.r1.8-313.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    CoFHAPI|item(API: CoFHAPI|item:1.8.9R1.2.0B1): mcjtylib-1.10-1.9.9.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    ProjectEAPI(API: ProjectEAPI:1.9.4-1.0.0): ProjectE-1.9.4-PE1.0.4B.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    StorageDrawersAPI|config(API: StorageDrawersAPI|config:1.7.10-1.2.0): StorageDrawers-1.9.4-3.2.1.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    CalculatorAPI(API: CalculatorAPI:1.9.4 - 1.0): Calculator-1.9.4-3.0.8.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    StorageDrawersAPI|event(API: StorageDrawersAPI|event:1.7.10-1.2.0): StorageDrawers-1.9.4-3.2.1.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    Baubles|API(API: Baubles|API:1.1.1.0): Baubles-1.9.4-1.2.1.0.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    JustEnoughItemsAPI(API: JustEnoughItemsAPI:3.1.0): jei_1.9.4-3.6.8.225.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    journeymap|client-api-display(API: journeymap|client-api-display:1.2): journeymap-1.9.4-5.2.4-unlimited.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    StorageDrawersAPI|pack(API: StorageDrawersAPI|pack:1.7.10-1.2.0): StorageDrawers-1.9.4-3.2.1.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    ChiselAPI(API: ChiselAPI:0.0.1): Chisel-MC1.9.4-0.0.6.33.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    journeymap|client-api-model(API: journeymap|client-api-model:1.2): journeymap-1.9.4-5.2.4-unlimited.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    journeymap|client-api(API: journeymap|client-api:1.2): journeymap-1.9.4-5.2.4-unlimited.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    journeymap|client-api-event(API: journeymap|client-api-event:1.2): journeymap-1.9.4-5.2.4-unlimited.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    StorageDrawersAPI|storage-attribute(API: StorageDrawersAPI|storage-attribute:1.7.10-1.2.0): StorageDrawers-1.9.4-3.2.1.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    StorageDrawersAPI|render(API: StorageDrawersAPI|render:1.7.10-1.2.0): StorageDrawers-1.9.4-3.2.1.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    journeymap|client-api-util(API: journeymap|client-api-util:1.2): journeymap-1.9.4-5.2.4-unlimited.jar ()
[23:53:58] [Client thread/DEBUG] [FML/]:    CraftingTweaks|API(API: CraftingTweaks|API:4.1): craftingtweaks-mc1.9.4-5.0.6.jar ()
```

Full log can be downloaded [here](https://github.com/SonarSonic/Calculator/files/398595/fml-client-latest.log.zip) (sorry for the Zip format, GitHub allows only Zip for blind uploads).

**Comment by hron84** [comment]
Additional note: I am not exactly sure which assimilator can be used for which tree. However, even if I did a wrong setup, assimilators should not crash the client, but instead do absolute nothing.

As I see, in [this line](https://github.com/SonarSonic/Calculator/blob/1.9.4/src/main/java/sonar/calculator/mod/common/tileentity/machines/TileEntityAssimilator.java#L254) you should check if the `block` is one of the leaves assimilator can handle, since the TreeHarvestRecipes will return with null if no harvesting recipe found. But the recipe lookup is not neccessary if assimilator cannot handle the leaves anyway.

**Comment by SonarSonic** [comment]
Fixed in dev

**Comment by hron84** [comment]
@SonarSonic This is why I like this mod. Quick fixes. :smile:
