### ISSUE TITLE
[1.10.2] Errors in server console

### ISSUE THREAD

**Issue by kwpugh** [SonarSonic/Calculator#164]
Forge: 2052
Mod: SonarCore-1.9.4-3.1.1.jar

Getting these messages in the server console

[09:33:57] [Server thread/ERROR] [FML]: A TileEntity AlgorithmSeparator(sonar.calculator.mod.common.tileentity.TileEntityMachine$AlgorithmSeperator) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.NullPointerException
        at sonar.core.common.tileentity.TileEntitySonar.isClient(TileEntitySonar.java:44) ~[TileEntitySonar.class:?]
        at sonar.core.common.tileentity.TileEntitySidedInventory.func_145839_a(TileEntitySidedInventory.java:19) ~[TileEntitySidedInventory.class:?]
        at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:123) [aqk.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:486) [atj.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:96) [ChunkIOProvider.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) [ChunkIOExecutor.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:115) [lr.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:86) [lr.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:132) [lr.class:?]
        at net.minecraft.world.World.func_72964_e(World.java:301) [aid.class:?]
        at net.minecraft.world.World.func_175726_f(World.java:296) [aid.class:?]
        at net.minecraft.world.World.func_180495_p(World.java:840) [aid.class:?]
        at net.minecraft.world.World.func_175627_a(World.java:3174) [aid.class:?]
        at net.minecraft.world.World.func_175676_y(World.java:3201) [aid.class:?]
        at net.minecraft.world.World.func_175651_c(World.java:3242) [aid.class:?]
        at net.minecraft.world.World.func_175687_A(World.java:3256) [aid.class:?]
        at crazypants.enderio.conduit.liquid.AbstractLiquidConduit.isConditionMetByExternalSignal(AbstractLiquidConduit.java:149) [AbstractLiquidConduit.class:?]
        at crazypants.enderio.conduit.liquid.AbstractLiquidConduit.autoExtractForDir(AbstractLiquidConduit.java:135) [AbstractLiquidConduit.class:?]
        at crazypants.enderio.conduit.liquid.LiquidConduit.doExtract(LiquidConduit.java:124) [LiquidConduit.class:?]
        at crazypants.enderio.conduit.liquid.LiquidConduit.updateEntity(LiquidConduit.java:94) [LiquidConduit.class:?]
        at crazypants.enderio.conduit.TileConduitBundle.doUpdate(TileConduitBundle.java:229) [TileConduitBundle.class:?]
        at com.enderio.core.common.TileEntityBase.func_73660_a(TileEntityBase.java:36) [TileEntityBase.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1802) [aid.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618) [ls.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]

**Comment by SonarSonic** [comment]
Thanks for reporting will be fixed in next SonarCore Update

**Comment by kwpugh** [comment]
additional related messages:

[01:14:46] [Server thread/ERROR]: Failed to load data for block entity StoneSeparator
java.lang.NullPointerException
        at sonar.core.common.tileentity.TileEntitySonar.isClient(TileEntitySonar.java:44) ~[TileEntitySonar.class:?]
        at sonar.core.common.tileentity.TileEntitySidedInventory.func_145839_a(TileEntitySidedInventory.java:19) ~[TileEntitySidedInventory.class:?]
        at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:123) [aqk.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:486) [atj.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:96) [ChunkIOProvider.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150) [ChunkIOExecutor.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:673) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
[01:14:46] [Server thread/ERROR] [FML]: A TileEntity StoneSeparator(sonar.calculator.mod.common.tileentity.TileEntityMachine$StoneSeperator) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.NullPointerException
        at sonar.core.common.tileentity.TileEntitySonar.isClient(TileEntitySonar.java:44) ~[TileEntitySonar.class:?]
        at sonar.core.common.tileentity.TileEntitySidedInventory.func_145839_a(TileEntitySidedInventory.java:19) ~[TileEntitySidedInventory.class:?]
        at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:123) [aqk.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:486) [atj.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:96) [ChunkIOProvider.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150) [ChunkIOExecutor.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:673) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
[01:14:46] [Server thread/ERROR]: Failed to load data for block entity AlgorithmSeparator
java.lang.NullPointerException
        at sonar.core.common.tileentity.TileEntitySonar.isClient(TileEntitySonar.java:44) ~[TileEntitySonar.class:?]
        at sonar.core.common.tileentity.TileEntitySidedInventory.func_145839_a(TileEntitySidedInventory.java:19) ~[TileEntitySidedInventory.class:?]
        at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:123) [aqk.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:486) [atj.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:96) [ChunkIOProvider.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150) [ChunkIOExecutor.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:673) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
[01:14:46] [Server thread/ERROR] [FML]: A TileEntity AlgorithmSeparator(sonar.calculator.mod.common.tileentity.TileEntityMachine$AlgorithmSeperator) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.NullPointerException
        at sonar.core.common.tileentity.TileEntitySonar.isClient(TileEntitySonar.java:44) ~[TileEntitySonar.class:?]
        at sonar.core.common.tileentity.TileEntitySidedInventory.func_145839_a(TileEntitySidedInventory.java:19) ~[TileEntitySidedInventory.class:?]
        at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:123) [aqk.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:486) [atj.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:96) [ChunkIOProvider.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150) [ChunkIOExecutor.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:673) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]

**Comment by SonarSonic** [comment]
Fixed in dev
