### ISSUE TITLE
TileEntity AnalysingChamber NPE

### ISSUE THREAD

**Issue by t3f** [SonarSonic/Calculator#165]
Hit this today.

```

[09:53:03] [Server thread/ERROR] [FML/]: A TileEntity AnalysingChamber(sonar.calculator.mod.common.tileentity.machines.TileEntityAnalysingChamber) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.NullPointerException
        at sonar.core.common.tileentity.TileEntitySonar.isClient(TileEntitySonar.java:44) ~[TileEntitySonar.class:?]
        at sonar.core.common.tileentity.TileEntitySidedInventory.func_145839_a(TileEntitySidedInventory.java:19) ~[TileEntitySidedInventory.class:?]
        at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:123) [aqk.class:?]

```

Full log @ https://gist.github.com/t3f/44654c8b293755d442d581f20096e3ad

**Comment by SonarSonic** [comment]
#164
