### ISSUE TITLE
Some machines crash the server after update

### ISSUE THREAD

**Issue by meatball0417** [SonarSonic/Calculator#216]
Please fill out the details below before contributing

 * Forge Version: 2221
 * Calculator Version: 1.10.2-3.1.7
 * SonarCore Version: 1.10.2-3.2.3
 * Multiplayer or Singleplayer: MP(crash at SP)
 * Crash Report Link: 
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.7.jar)
  LoadingHook (Mekanism-1.10.2-9.2.1.298.jar)
  FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  ForgelinPlugin (Forgelin-1.2.0.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.7.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  AppleCore (AppleCore-mc1.10.2-2.1.0.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.7.jar)
  IC2core (industrialcraft-2-2.6.142-ex110.jar)
  Plugin (NotEnoughIDs-1.5.3.jar)
  LoadingPlugin (Bloodmoon-MC1.10.2-1.5.1.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.5.3-anarchy.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.2.198-universal.jar)
  Brandon's Core (BrandonsCore-1.10.2-2.1.3.82-universal.jar)
  Default Options (DefaultOptions_1.10.2-6.1.5.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.65-beta.jar)
  LoadingPlugin (Quark-r1.1-70.jar)
  RebornCoreASM (RebornCore-1.10.2-2.13.2.114-universal.jar)
  MalisisCorePlugin (malisiscore-1.10.2-4.2.10.jar)
  AppEngCore (appliedenergistics2-rv4-alpha-11.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.1.6.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.339.jar)
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 2/11/17 4:10 PM
Description: Unexpected error

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at net.minecraft.inventory.Container.func_75139_a(Container.java:113)
	at assets.recipehandler.CraftingHandler.getResultSlot(CraftingHandler.java:118)
	at assets.recipehandler.ClientEventHandler.keyDown(ClientEventHandler.java:87)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_840_ClientEventHandler_keyDown_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:344)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1851)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at net.minecraft.inventory.Container.func_75139_a(Container.java:113)
	at assets.recipehandler.CraftingHandler.getResultSlot(CraftingHandler.java:118)
	at assets.recipehandler.ClientEventHandler.keyDown(ClientEventHandler.java:87)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_840_ClientEventHandler_keyDown_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:344)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['sleix6102060'/189424, l='MpServer', x=259.95, y=69.00, z=-140.98]]
	Chunk stats: MultiplayerChunkCache: 420, 420
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 13083801 game time, 1613729 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 77 total; [EntityBat['Bat'/445956, l='MpServer', x=271.46, y=29.28, z=-154.12], EntityItem['item.item.arrow'/439054, l='MpServer', x=203.60, y=52.00, z=-164.65], EntityWitch['Witch'/448526, l='MpServer', x=204.50, y=52.00, z=-156.50], EntityBat['Bat'/428559, l='MpServer', x=265.64, y=61.10, z=-116.75], EntityItem['item.item.ma.inferium_essence'/439055, l='MpServer', x=203.13, y=52.00, z=-164.88], EntityZombie['Zombie'/446742, l='MpServer', x=255.50, y=59.00, z=-123.20], EntityZombie['Zombie'/446741, l='MpServer', x=250.74, y=56.00, z=-126.47], EntityBabySkeleton['Baby Skeleton'/448038, l='MpServer', x=318.50, y=39.00, z=-121.50], EntitySheep['Sheep'/411175, l='MpServer', x=331.55, y=68.22, z=-104.49], EntityBabySkeleton['Baby Skeleton'/448039, l='MpServer', x=320.50, y=39.00, z=-122.50], EntityZombie['Zombie'/448037, l='MpServer', x=319.35, y=39.00, z=-123.65], EntityCow['Cow'/249383, l='MpServer', x=318.60, y=62.42, z=-207.45], EntityZombie['Zombie'/443695, l='MpServer', x=276.50, y=26.00, z=-61.50], EntityXPOrb['Experience Orb'/445231, l='MpServer', x=302.25, y=86.30, z=-222.50], EntitySheep['Sheep'/411176, l='MpServer', x=333.46, y=68.58, z=-106.55], EntitySheep['Sheep'/411177, l='MpServer', x=329.85, y=68.52, z=-108.13], EntityBat['Bat'/433221, l='MpServer', x=265.43, y=61.10, z=-116.75], EntityBat['Bat'/442176, l='MpServer', x=271.93, y=29.04, z=-148.78], EntityConcussionCreeper['Concussion Creeper'/448335, l='MpServer', x=217.56, y=19.00, z=-108.20], EntityZombie['Zombie'/445271, l='MpServer', x=290.50, y=41.00, z=-188.50], EntityZombie['Zombie'/448338, l='MpServer', x=212.50, y=52.00, z=-155.50], EntityCreeper['Creeper'/448339, l='MpServer', x=209.29, y=52.00, z=-154.51], EntityItem['item.item.string'/442975, l='MpServer', x=203.63, y=52.00, z=-164.88], EntitySkeleton['Skeleton'/446557, l='MpServer', x=276.50, y=60.00, z=-109.50], EntityWorm['entity.actuallyadditions.actuallyadditions.worm.name'/353, l='MpServer', x=202.50, y=75.50, z=-136.50], EntityItem['item.item.sulphur'/445287, l='MpServer', x=203.13, y=52.00, z=-158.43], EntityBat['Bat'/448615, l='MpServer', x=331.52, y=42.31, z=-179.01], EntitySheep['Sheep'/354, l='MpServer', x=270.27, y=72.00, z=-61.52], EntityXPOrb['Experience Orb'/446053, l='MpServer', x=302.25, y=86.30, z=-222.49], EntitySkeleton['Skeleton'/446821, l='MpServer', x=334.50, y=40.00, z=-183.50], EntityPig['Pig'/358, l='MpServer', x=223.75, y=77.00, z=-91.52], EntityZombie['Zombie'/447342, l='MpServer', x=305.50, y=40.00, z=-123.50], EntitySkeleton['Skeleton'/448364, l='MpServer', x=268.50, y=61.00, z=-118.50], EntityDummy['entity.testdummy.Dummy.name'/364, l='MpServer', x=238.50, y=72.00, z=-162.50], EntityZombie['Zombie'/448362, l='MpServer', x=274.50, y=61.00, z=-112.50], EntityZombie['Zombie'/448363, l='MpServer', x=275.50, y=61.00, z=-113.50], EntitySkeleton['Skeleton'/413033, l='MpServer', x=240.56, y=66.00, z=-164.19], EntityZombie['Zombie'/448361, l='MpServer', x=274.50, y=61.00, z=-111.50], EntityXPOrb['Experience Orb'/440178, l='MpServer', x=301.17, y=86.59, z=-222.50], EntityHorse['Skeleton Horse'/373, l='MpServer', x=180.99, y=63.09, z=-176.97], EntityXPOrb['Experience Orb'/440179, l='MpServer', x=302.25, y=86.30, z=-222.50], EntitySheep['Sheep'/374, l='MpServer', x=225.28, y=75.00, z=-61.54], EntityCow['Cow'/376, l='MpServer', x=296.53, y=70.00, z=-183.85], EntityBat['Bat'/433535, l='MpServer', x=271.90, y=53.36, z=-119.33], EntityConcussionCreeper['Concussion Creeper'/447357, l='MpServer', x=255.11, y=59.00, z=-116.46], EntityZombie['Zombie'/447354, l='MpServer', x=263.47, y=59.00, z=-111.80], EntitySpider['Spider'/448376, l='MpServer', x=302.50, y=39.00, z=-128.50], EntitySkeleton['Skeleton'/448377, l='MpServer', x=303.50, y=39.00, z=-126.50], EntityItem['item.item.arrow'/445319, l='MpServer', x=203.61, y=52.00, z=-162.41], EntitySkeleton['Skeleton'/445312, l='MpServer', x=338.50, y=33.00, z=-206.50], EntityBat['Bat'/433537, l='MpServer', x=259.49, y=55.10, z=-122.45], EntityZombie['Zombie'/448397, l='MpServer', x=204.50, y=52.00, z=-163.50], EntitySkeleton['Skeleton'/448150, l='MpServer', x=273.50, y=21.00, z=-72.50], EntityCreeper['Creeper'/435870, l='MpServer', x=262.83, y=53.00, z=-116.55], EntitySpider['Spider'/448414, l='MpServer', x=205.50, y=52.00, z=-161.50], EntityCreeper['Creeper'/447640, l='MpServer', x=269.50, y=53.00, z=-116.50], EntityItem['item.item.sulphur'/437412, l='MpServer', x=203.13, y=52.00, z=-155.92], EntityPlayerSP['sleix6102060'/189424, l='MpServer', x=259.95, y=69.00, z=-140.98], EntityZombie['Zombie'/442273, l='MpServer', x=277.19, y=47.00, z=-143.44], EntityCreeper['Creeper'/445874, l='MpServer', x=277.50, y=27.00, z=-63.50], EntityEnderman['Enderman'/446640, l='MpServer', x=282.50, y=37.00, z=-88.50], EntityZombie['Zombie'/446641, l='MpServer', x=286.50, y=37.00, z=-89.50], EntitySkeleton['Skeleton'/438201, l='MpServer', x=266.51, y=53.00, z=-115.79], EntityBat['Bat'/447161, l='MpServer', x=235.40, y=27.57, z=-97.07], EntityAncientGolem['Ancient Golem'/447430, l='MpServer', x=204.97, y=52.00, z=-154.57], EntityItem['item.item.string'/444864, l='MpServer', x=203.13, y=52.00, z=-158.49], EntityBabySkeleton['Baby Skeleton'/445898, l='MpServer', x=206.50, y=30.00, z=-105.50], EntityBat['Bat'/442070, l='MpServer', x=270.48, y=62.10, z=-117.33], EntityItem['item.item.rottenFlesh'/436179, l='MpServer', x=203.13, y=52.00, z=-163.79], EntityPig['Pig'/410579, l='MpServer', x=314.73, y=71.00, z=-67.50], EntityZombie['Zombie'/448467, l='MpServer', x=294.50, y=34.00, z=-98.50], EntityItem['item.item.bone'/440025, l='MpServer', x=203.13, y=52.00, z=-164.87], EntityZombie['Zombie'/447463, l='MpServer', x=291.50, y=34.00, z=-100.50], EntityZombie['Zombie'/448482, l='MpServer', x=291.50, y=25.00, z=-66.50], EntityZombie['Zombie'/448483, l='MpServer', x=288.50, y=25.00, z=-64.50], EntityCreeper['Creeper'/448480, l='MpServer', x=291.50, y=25.00, z=-66.50], EntityCreeper['Creeper'/448481, l='MpServer', x=292.50, y=25.00, z=-66.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)
 * Description: 
Everytime I tried to place a stone seperator it crashes like that.

**Comment by SonarSonic** [comment]
Fixed in dev. Update Calculator to 3.1.8
