### ISSUE TITLE
Crash when placing blocks

### ISSUE THREAD

**Issue by bryce-happel-walton** [SonarSonic/Calculator#218]
Please fill out the details below before contributing

 * Forge Version: forge-12.18.3.2221
 * Calculator Version: Calculator-1.10.2-3.1.7
 * SonarCore Version: Sonar-Core-1.10.2-3.2.3
 * Multiplayer or Singleplayer: Singleplayer
 * Crash Report Link: Not sure where to find this
 * Affected Features: I can't play the world affected
 * Description: When I placed an Extraction Chamber or Precision Chamber the game crashed

[crash-2017-02-13_14.52.17-client.txt](https://github.com/SonarSonic/Calculator/files/772255/crash-2017-02-13_14.52.17-client.txt)

Description: Unexpected error

java.lang.NoSuchMethodError: sonar.core.upgrades.UpgradeInventory.<init>(I[Ljava/lang/Object;)V
	at sonar.calculator.mod.common.tileentity.TileEntityProcess.<init>(TileEntityProcess.java:42)
	at sonar.calculator.mod.common.tileentity.TileEntityAbstractProcess.<init>(TileEntityAbstractProcess.java:19)
	at sonar.calculator.mod.common.tileentity.TileEntityMachine$DualOutput.<init>(TileEntityMachine.java:28)
	at sonar.calculator.mod.common.tileentity.TileEntityMachine$ExtractionChamber.<init>(TileEntityMachine.java:210)
	at sonar.calculator.mod.common.block.SmeltingBlock$BlockTypes.getTile(SmeltingBlock.java:64)
	at sonar.calculator.mod.common.block.SmeltingBlock.func_149915_a(SmeltingBlock.java:147)
	at net.minecraft.block.Block.createTileEntity(Block.java:1206)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:621)
	at net.minecraft.world.World.func_180501_a(World.java:331)
	at net.minecraft.client.multiplayer.WorldClient.func_180501_a(WorldClient.java:621)
	at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:165)
	at net.minecraft.item.ItemBlock.func_180614_a(ItemBlock.java:54)
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:145)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:454)
	at PlayerControllerOF.func_187099_a(PlayerControllerOF.java:88)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1518)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by SonarSonic** [comment]
Fixed in dev. Update Calculator to 3.1.8

**Comment by bryce-happel-walton** [comment]
Where might I find 3.1.8? In Curse there's only 3.1.7 and I only see 3.1.7 on GitHub.

**Comment by SonarSonic** [comment]
@MrTaco9001 should be up now

**Comment by bryce-happel-walton** [comment]
Thank you! Great mod btw
