### ISSUE TITLE
Crash with extraction/precision chamber

### ISSUE THREAD

**Issue by bryce-happel-walton** [SonarSonic/Calculator#219]
Forge Version: forge-12.18.3.2221
Calculator Version: Calculator-1.10.2-3.1.8
SonarCore Version: Sonar-Core-1.10.2-3.2.3
Multiplayer or Singleplayer: Singleplayer
Crash Report Link: Not sure where to find this
Affected Features: I can't play the world affected
Description: When I put items in an extraction/precision chamber the game crashes

[crash-2017-02-13_17.16.56-client.txt](https://github.com/SonarSonic/Calculator/files/772609/crash-2017-02-13_17.16.56-client.txt)
[crash-2017-02-13_17.25.58-client.txt](https://github.com/SonarSonic/Calculator/files/772607/crash-2017-02-13_17.25.58-client.txt)

Description: Updating screen events

java.lang.AbstractMethodError: sonar.core.inventory.AbstractSonarInventory.func_70296_d()V
	at sonar.core.inventory.SonarInventory.func_70296_d(SonarInventory.java:21)
	at sonar.core.inventory.AbstractSonarInventory.func_70299_a(AbstractSonarInventory.java:144)
	at sonar.core.common.tileentity.TileEntityInventory.func_70299_a(TileEntityInventory.java:80)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:72)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:191)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:550)
	at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:565)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:627)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_184098_a(GuiContainer.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:15)
	at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:506)
	at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:579)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:558)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by bryce-happel-walton** [comment]
Update: Happens with every inventory gui where you can put items in.

**Comment by Ommina** [comment]
Indeed.  Crash with Advanced Greenhouse brought me here.

http://pastebin.com/dr6RayT5 -- but it looks pretty much the same (though no NEI in the stack).

Calculator-1.10.2-3.1.8.jar
SonarCore-1.10.2-3.2.3.jar

Multiplayer.

**Comment by SonarSonic** [comment]
Fixed in dev
