### ISSUE TITLE
Docking station crash and non importable

### ISSUE THREAD

**Issue by meatball0417** [SonarSonic/Calculator#222]
Please fill out the details below before contributing

 * Forge Version: 2221
 * Calculator Version: 1.10.2.3.1.8
 * SonarCore Version: 1.10.2.3.2.3
 * Multiplayer or Singleplayer: MP
 * Crash Report Link: Description: Updating screen events

java.lang.AbstractMethodError: sonar.core.inventory.AbstractSonarInventory.func_70296_d()V
	at sonar.core.inventory.SonarInventory.func_70296_d(SonarInventory.java:21)
	at sonar.core.inventory.AbstractSonarInventory.func_70298_a(AbstractSonarInventory.java:121)
	at sonar.core.common.tileentity.TileEntityInventory.func_70298_a(TileEntityInventory.java:72)
	at net.minecraft.inventory.Slot.func_75209_a(Slot.java:100)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:317)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:550)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:630)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:389)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:548)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at sonar.core.inventory.SonarInventory.func_70296_d(SonarInventory.java:21)
	at sonar.core.inventory.AbstractSonarInventory.func_70298_a(AbstractSonarInventory.java:121)
	at sonar.core.common.tileentity.TileEntityInventory.func_70298_a(TileEntityInventory.java:72)
	at net.minecraft.inventory.Slot.func_75209_a(Slot.java:100)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:317)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:550)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:630)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:389)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:548)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517)
 * Affected Features: 
Docking station
 * Description: \Crash when trying to hopper blaze rods into the left side of Docking station , at first it only render 1 blaze rod even if I hoppered a stack of it, then it crashed.Also the front and back side can't be imported by hopper or conduicts.

**Comment by SonarSonic** [comment]
Update SonarCore and Calculator.
