### ISSUE TITLE
1.10.2 Basic Greenhouse crash upon build completion

### ISSUE THREAD

**Issue by ZheIncknight** [SonarSonic/Calculator#281]
Please fill out the details below before contributing

 * Forge Version: 12.18.3.2477
 * Calculator Version: 1.10.2-3.2.3
 * SonarCore Version: 1.10.2-3.2.9
 * Multiplayer or Singleplayer: Singleplayer
 * Crash Report Link: 
[crash-2017-09-15_23.06.16-server.txt](https://github.com/SonarSonic/Calculator/files/1307750/crash-2017-09-15_23.06.16-server.txt)

 * Affected Features: Basic Greenhouse
 * Description: When the Basic Greenhouse finishes its construction it crashes the game. I start construction of the green house by shift right clicking because the build ui does not work.

**Comment by hottentottententententoonstelling** [comment]
This is the exact issue as #279, which is fixed, but there is unfortunately no release yet which includes this fix

**Comment by hottentottententententoonstelling** [comment]
SonarSonic has released a new version on curseforge which fixes this

**Comment by FalkW** [comment]
Roger that, same issue here.

PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at sonar.core.integration.planting.vanilla.Planter.canTierPlant(Planter.java:27)
	at sonar.calculator.mod.common.tileentity.TileEntityGreenhouse.getPlanter(TileEntityGreenhouse.java:228)
	at sonar.calculator.mod.common.tileentity.TileEntityGreenhouse.plantCrops(TileEntityGreenhouse.java:208)
	at sonar.calculator.mod.common.tileentity.TileEntityBuildingGreenhouse.func_73660_a(TileEntityBuildingGreenhouse.java:69)
	at sonar.calculator.mod.common.tileentity.machines.TileEntityBasicGreenhouse.func_73660_a(TileEntityBasicGreenhouse.java:45)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at sonar.core.integration.planting.vanilla.Planter.canTierPlant(Planter.java:27)
	at sonar.calculator.mod.common.tileentity.TileEntityGreenhouse.getPlanter(TileEntityGreenhouse.java:228)
	at sonar.calculator.mod.common.tileentity.TileEntityGreenhouse.plantCrops(TileEntityGreenhouse.java:208)
	at sonar.calculator.mod.common.tileentity.TileEntityBuildingGreenhouse.func_73660_a(TileEntityBuildingGreenhouse.java:69)
	at sonar.calculator.mod.common.tileentity.machines.TileEntityBasicGreenhouse.func_73660_a(TileEntityBasicGreenhouse.java:45)

**Comment by SonarSonic** [comment]
Latest version fixes this issue.
