### ISSUE TITLE
1.12.1 sonar core crash

### ISSUE THREAD

**Issue by Joshiso** [SonarSonic/Calculator#294]
Please fill out the details below before contributing

 * Forge Version: 1.12.1-14.22.1.2485
 * Calculator Version: 14.22.1.2485
 * SonarCore Version: 1.12.1
 * Multiplayer or Singleplayer: singleplayer
 * Crash Report Link: The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from SonarCore (sonarcore)
 * Affected Features:all
 * Description:---- Minecraft Crash Report ----

WARNING: coremods are present:
  ItemPatchingLoader (ItemPhysic-Mod-Full-1.12.1.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.108.jar)
  SFRCore (Solar-Flux-Reborn-Mod-1.12.1.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-74-core.jar)
  CreativePatchingLoader (CreativeCore-1.12.1.jar)
  LoadingPlugin (Quark-Mod-1.12.1.jar)
  CoreMod (Aroma1997Core-1.12.1-1.3.0.0.b124.jar)
  HammerCoreCore (Hammer-Core-1.12.1.jar)
  AstralCore (astralsorcery-1.12.2-1.7.2.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 10/29/17 8:27 PM
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at com.feed_the_beast.ftbl.api_impl.ForgeTeam.getTitle(ForgeTeam.java:323)
	at com.feed_the_beast.ftbu.handlers.FTBUPlayerEventHandler.updateChunkMessage(FTBUPlayerEventHandler.java:150)
	at com.feed_the_beast.ftbu.handlers.FTBUPlayerEventHandler.onChunkChanged(FTBUPlayerEventHandler.java:130)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_445_FTBUPlayerEventHandler_onChunkChanged_EnteringChunk.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraft.world.chunk.Chunk.func_76612_a(Chunk.java:738)
	at net.minecraft.world.World.func_72866_a(World.java:2032)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:833)
	at net.minecraft.world.World.func_72870_g(World.java:1946)
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:643)
	at net.minecraft.world.World.func_72939_s(World.java:1730)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.feed_the_beast.ftbl.api_impl.ForgeTeam.getTitle(ForgeTeam.java:323)
	at com.feed_the_beast.ftbu.handlers.FTBUPlayerEventHandler.updateChunkMessage(FTBUPlayerEventHandler.java:150)
	at com.feed_the_beast.ftbu.handlers.FTBUPlayerEventHandler.onChunkChanged(FTBUPlayerEventHandler.java:130)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_445_FTBUPlayerEventHandler_onChunkChanged_EnteringChunk.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraft.world.chunk.Chunk.func_76612_a(Chunk.java:738)
	at net.minecraft.world.World.func_72866_a(World.java:2032)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:833)
	at net.minecraft.world.World.func_72870_g(World.java:1946)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 258
	Entity Name: Player
	Entity's Exact location: -476.14, 73.62, -719.49
	Entity's Block location: World: (-477,73,-720), Chunk: (at 3,4,0 in -30,-45; contains blocks -480,0,-720 to -465,255,-705), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:643)
	at net.minecraft.world.World.func_72939_s(World.java:1730)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614)

-- Affected level --
Details:
	Level name: Modded World
	All players: 1 total; [EntityPlayerMP['Player'/258, l='Modded World', x=-476.14, y=73.62, z=-719.49]]
	Chunk stats: ServerChunkCache: 421 Drop: 0
	Level seed: -2929770751205690064
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-471,70,-718), Chunk: (at 9,4,2 in -30,-45; contains blocks -480,0,-720 to -465,255,-705), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
	Level time: 1654479 game time, 1000 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 14043 (now: true), thunder time: 61342 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.1
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1395977640 bytes (1331 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.41 Powered by Forge 14.22.1.2485 Optifine OptiFine_1.12.1_HD_U_C5 67 mods loaded, 66 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                    | Version               | Source                                              | Signature                                |
	|:--------- |:--------------------- |:--------------------- |:--------------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft             | 1.12.1                | minecraft.jar                                       | None                                     |
	| UCHIJAAAA | mcp                   | 9.19                  | minecraft.jar                                       | None                                     |
	| UCHIJAAAA | FML                   | 8.0.99.99             | forge-1.12.1-14.22.1.2485.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                 | 14.22.1.2485          | forge-1.12.1-14.22.1.2485.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | creativecoredummy     | 1.0.0                 | minecraft.jar                                       | None                                     |
	| UCHIJAAAA | itemphysic            | 1.4.0                 | minecraft.jar                                       | None                                     |
	| UCHIJAAAA | mercurius_updater     | 1.0                   | MercuriusUpdater-1.12.1.jar                         | None                                     |
	| UCHIJAAAA | actuallyadditions     | 1.12.1-r120           | Actually-Additions-Mod-1.12.1.jar                   | None                                     |
	| UCHIJAAAA | aroma1997core         | 1.3.0.0.b124          | Aroma1997Core-1.12.1-1.3.0.0.b124.jar               | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UCHIJAAAA | aroma1997sdimension   | 2.0.0.0.b57           | Aroma1997s-Dimensional-World-1.12.1-2.0.0.0.b57.jar | None                                     |
	| UCHIJAAAA | astralsorcery         | 1.7.2                 | astralsorcery-1.12.2-1.7.2.jar                      | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| UCHIJAAAA | quark                 | r1.3-110              | Quark-Mod-1.12.1.jar                                | None                                     |
	| UCHIJAAAA | autoreglib            | 1.3-13                | AutoRegLib-1.12.jar                                 | None                                     |
	| UCHIJAAAA | betterbuilderswands   | 0.11.1                | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar     | None                                     |
	| UCHIJAAAA | bookshelf             | 2.1.441               | Bookshelf-1.12.1-2.1.441.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | codechickenlib        | 3.1.3.313             | CodeChickenLib-1.12.1.jar                           | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | redstoneflux          | 2.0.1                 | Redstone-Flux-API-1.12.jar                          | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJAAAA | brandonscore          | 2.3.2                 | Brandons-Core-1.12.1.jar                            | None                                     |
	| UCHIJAAAA | chancecubes           | 1.12.1-3.0.1.203      | ChanceCubes-1.12.1-3.0.1.203.jar                    | None                                     |
	| UCHIJAAAA | cofhcore              | 4.3.4                 | CoFHCore-1.12-4.3.4.12-universal.jar                | None                                     |
	| UCHIJAAAA | cofhworld             | 1.0.1                 | CoFHWorld-1.12-1.0.1.8-universal.jar                | None                                     |
	| UCHIJAAAA | cyclopscore           | 0.10.19               | CyclopsCore-1.12.1.jar                              | None                                     |
	| UCHIJAAAA | colossalchests        | 1.6.7                 | Colossal-Chests-Mod-1.12.1.jar                      | None                                     |
	| UCHIJAAAA | cosmeticarmorreworked | 1.12.1-v1             | CosmeticArmorReworked-1.12.1-v1.jar                 | None                                     |
	| UCHIJAAAA | creativecore          | 1.7.4                 | CreativeCore-1.12.1.jar                             | None                                     |
	| UCHIJAAAA | cucumber              | 1.0.2                 | Cucumber-Mod-1.12.2.jar                             | None                                     |
	| UCHIJAAAA | jei                   | 4.7.5.88              | jei_1.12.1-4.7.5.88.jar                             | None                                     |
	| UCHIJAAAA | cyclicmagic           | 1.8.4                 | Cyclic-1.12-1.8.4.jar                               | None                                     |
	| UCHIJAAAA | torohealthmod         | 1.12.1-11             | Damage-Indicators-1.12.1.jar                        | None                                     |
	| UCHIJAAAA | darkutils             | 1.7.171               | DarkUtils-1.12.1-1.7.171.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | draconicevolution     | 2.3.3                 | Draconic-Evolution-Mod-1.12.1.jar                   | None                                     |
	| UCHIJAAAA | enderstorage          | 2.4.0.122             | Ender-Storage-Mod-1.12.jar                          | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | extrautils2           | 1.0                   | Extra-Utilities-Mod-1.12.1.jar                      | None                                     |
	| UCHIJAAAA | mekanism              | 9.4.1                 | Mekanism-1.12.1-9.4.1.326.jar                       | None                                     |
	| UCHIJAAAA | sonarcore             | 5.0.2                 | sonarcore-1.12.2-5.0.2.jar                          | None                                     |
	| UCHIJAAAA | fluxnetworks          | 3.0.0                 | fluxnetworks-1.12.1-3.0.0 (2).jar                   | None                                     |
	| UCHIJAAAA | ftbl                  | 0.0.0                 | FTBLib-4.1.3.jar                                    | None                                     |
	| UCHIJAAAA | ftbu                  | 0.0.0                 | FTBUtilities-4.1.3.jar                              | None                                     |
	| UCHIJAAAA | hammercore            | 1.9.4.7               | Hammer-Core-1.12.1.jar                              | None                                     |
	| UCHIJAAAA | ichunutil             | 7.0.2                 | iChun-Util-Mod-1.12.2.jar                           | None                                     |
	| UCHIJAAAA | theoneprobe           | 1.4.17                | theoneprobe-1.12-1.4.17.jar                         | None                                     |
	| UCHIJAAAA | immersiveengineering  | 0.12-74               | Immersive-Engineering-Mod-1.12.1.jar                | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHIJAAAA | inventorytweaks       | 1.63+beta.108.6ff67c4 | InventoryTweaks-1.63+beta.108.jar                   | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | ironchest             | 1.12-7.0.31.818       | Iron-Chests-Mod-1.12.2.jar                          | None                                     |
	| UCHIJAAAA | journeymap            | 1.12.1-5.5.0          | JourneyMap-Mod-1.12.1-Unlimited.jar                 | None                                     |
	| UCHIJAAAA | levelup2              | ${version}            | Levels-Mod-1.12.1.jar                               | None                                     |
	| UCHIJAAAA | moreoverlays          | 1.12                  | More-Overlays-Mod-1.12.jar                          | None                                     |
	| UCHIJAAAA | mysticalagriculture   | 1.6.4                 | Mystical-Agriculture-Mod-1.12.1.jar                 | None                                     |
	| UCHIJAAAA | powerinventory        | 2.3.1                 | Overpowered-Inventory-Mod-1.12.1.jar                | None                                     |
	| UCHIJAAAA | harvestcraft          | 1.12.1b               | Pam's HarvestCraft 1.12.1b.jar                      | None                                     |
	| UCHIJAAAA | portalgun             | 7.0.0                 | PortalGun-1.12.2.jar                                | None                                     |
	| UCHIJAAAA | reborncore            | 3.4.3.114             | RebornCore-1.12.1.jar                               | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UCHIJAAAA | quantumstorage        | 4.4.0                 | Quantum-Storage-Mod-1.12.1.jar                      | None                                     |
	| UCHIJAAAA | refinedstorage        | 1.5.17                | refinedstorage-1.5.17.jar                           | None                                     |
	| UCHIJAAAA | refinedstorageaddons  | 0.1.1                 | refinedstorageaddons-0.1.1.jar                      | None                                     |
	| UCHIJAAAA | rftools               | 6.12                  | RFTools-Mod-1.12.jar                                | None                                     |
	| UCHIJAAAA | solarfluxreborn       | 3.40r                 | Solar-Flux-Reborn-Mod-1.12.1.jar                    | None                                     |
	| UCHIJAAAA | thermalfoundation     | 2.3.4                 | ThermalFoundation-1.12-2.3.4.13-universal.jar       | None                                     |
	| UCHIJAAAA | thermaldynamics       | 2.3.4                 | ThermalDynamics-1.12-2.3.4.11-universal.jar         | None                                     |
	| UCHIJAAAA | thermalexpansion      | 5.3.4                 | ThermalExpansion-1.12-5.3.4.16-universal.jar        | None                                     |
	| UCHIJAAAA | tp                    | 1.12                  | tinyprogressions-1.12-3.2.6.jar                     | None                                     |
	| UCHIJAAAA | torchmaster           | 1.5.2.40              | TorchMaster-Mod-1.12.1.jar                          | None                                     |
	| UCHIJAAAA | veinminer             | 0.38.1                | Vein-Miner-Mod-1.12.jar                             | None                                     |
	| UCHIJAAAA | veinminermodsupport   | 0.38.1                | Vein-Miner-Mod-1.12.jar                             | None                                     |
	| UCHIJAAAA | vtweaks               | 1.4.11.3              | VTweaks-1.12-1.4.11.3.jar                           | None                                     |
	| UCHIJAAAA | worldedit             | 6.1.8                 | WorldEdit-1.12.jar                                  | None                                     |
	| UD        | solarfluxreborncore   | 3.40r                 | minecraft.jar                                       | None                                     |

	Loaded coremods (and transformers): 
ItemPatchingLoader (ItemPhysic-Mod-Full-1.12.1.jar)
  com.creativemd.itemphysic.ItemTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.108.jar)
  invtweaks.forge.asm.ContainerTransformer
SFRCore (Solar-Flux-Reborn-Mod-1.12.1.jar)
  com.pengu.solarfluxreborn.core.SFRSerializedTransformer
IELoadingPlugin (ImmersiveEngineering-0.12-74-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
CreativePatchingLoader (CreativeCore-1.12.1.jar)
  
LoadingPlugin (Quark-Mod-1.12.1.jar)
  vazkii.quark.base.asm.ClassTransformer
CoreMod (Aroma1997Core-1.12.1-1.3.0.0.b124.jar)
  
HammerCoreCore (Hammer-Core-1.12.1.jar)
  com.pengu.hammercore.asm.HammerCoreTransformer
AstralCore (astralsorcery-1.12.2-1.7.2.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.4.3.114
		Runtime Debofucsation 1
		RenderEngine: 1
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Player'/258, l='Modded World', x=-476.14, y=73.62, z=-719.49]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.1_HD_U_C5
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.3.0 - Build 10.18.14.4264
	OpenGlRenderer: Intel(R) HD Graphics 4600
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by SonarSonic** [comment]
can you send the entire log?

**Comment by Joshiso** [comment]
if you can help that would mean alot
