### ISSUE TITLE
Server crash when recharging Basic terrain module

### ISSUE THREAD

**Issue by DBotThePony** [SonarSonic/Calculator#311]
* Forge Version: 2538 build
 * Calculator Version: 5.0.1
 * SonarCore Version: 5.0.2
 * Multiplayer or Singleplayer: multiplayer
 * Crash Report Link: https://i.dbot.serealia.ca/2017/11/crash-2017-11-23_19.15.56-server.txt
```
java.lang.NullPointerException: Ticking block entity
    at sonar.core.network.sync.SyncItemEnergyStorage.markChanged(SyncItemEnergyStorage.java:43)
    at sonar.core.network.sync.SyncEnergyStorage.addEnergy(SyncEnergyStorage.java:172)
    at sonar.core.network.sync.SyncEnergyStorage.givePower(SyncEnergyStorage.java:234)
    at mekanism.common.util.ChargeUtils.charge(ChargeUtils.java:103)
    at mekanism.common.tile.TileEntityEnergyCube.onUpdate(TileEntityEnergyCube.java:90)
    at mekanism.common.tile.prefab.TileEntityBasicBlock.func_73660_a(TileEntityBasicBlock.java:79)
    at net.minecraft.world.World.func_72939_s(World.java:1829)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
    at java.lang.Thread.run(Unknown Source)
```

Server is unable to start until module is removed from energy cube using mcedit

**Comment by AEnterprise** [comment]
please do not use terms like 'latest' in your report but fill in the exact version numbers
also please provide the full crashlog, that has more info that just that one stacktrace (like a full modlist with version numbers and more, this makes tracing things down easier)

**Comment by DBotThePony** [comment]
I didnt provided exact version numbers because no versions was released in >month, but sure i will provide exact infos when i get home.

**Comment by AEnterprise** [comment]
the problem with 'latest' is that we cannot know if you actually checked for new releases, or if it's the 'latest' of a pack you are playing, over the years i have seen a lot of users who claim to use latest but upon further digging (or just looking at the version in the crash report) it turns out they are running a version that is seriously outdated, or if a report isn't fixed/looked at instantly there might be a newer version released after the report

**Comment by DBotThePony** [comment]
* Forge Version: 2538 build
 * Calculator Version: 5.0.1
 * SonarCore Version: 5.0.2
 * Multiplayer or Singleplayer: multiplayer
 * Crash Report Link: https://i.dbot.serealia.ca/2017/11/crash-2017-11-23_19.15.56-server.txt

**Comment by SonarSonic** [comment]
Fixed in dev
