### ISSUE TITLE
Fabrication Chamber/ Not working & Crash

### ISSUE THREAD

**Issue by djpanda** [SonarSonic/Calculator#314]
Please fill out the details below before contributing

 * Forge Version: 14.23.1.2556
 * Calculator Version: 5.0.1
 * SonarCore Version: 5.0.2
 * Multiplayer or Singleplayer: Multiplayer
 * Crash Report : 
[19:30:35] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: io.netty.util.IllegalReferenceCountException: refCnt: 0
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_151]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_151]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1408) ~[AbstractByteBuf.class:?]
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1394) ~[AbstractByteBuf.class:?]
	at io.netty.buffer.AbstractByteBuf.readShort(AbstractByteBuf.java:706) ~[AbstractByteBuf.class:?]
	at net.minecraft.network.PacketBuffer.readShort(PacketBuffer.java:874) ~[gy.class:?]
	at net.minecraft.network.PacketBuffer.func_150791_c(PacketBuffer.java:350) ~[gy.class:?]
	at net.minecraftforge.fml.common.network.ByteBufUtils.readItemStack(ByteBufUtils.java:194) ~[ByteBufUtils.class:?]
	at sonar.calculator.mod.common.tileentity.machines.TileEntityFabricationChamber.readPacket(TileEntityFabricationChamber.java:200) ~[TileEntityFabricationChamber.class:?]
	at sonar.core.network.PacketByteBuf$Handler.lambda$processMessage$0(PacketByteBuf.java:64) ~[PacketByteBuf$Handler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_151]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
 * Description: From time to time the Client crashes and the placed Fabrication Chamber doesn´t work next to the Storage Chamber.. it only say´s "NO RECIPE" for every item.

**Comment by SonarSonic** [comment]
Fixed in dev
